server:
  port: 3208

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itwhy?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 11521
  jackson:
    generator:
      write_numbers_as_strings: true


mybatis-plus:
  mapper-locations:
    - classpath*:com/snowtraces/itwhy**/mapping/*.xml

